name: Daily build tarballs

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, aosc-os, x64]

    steps:
      - name: Install aoscbootstrap
        run: yes | sudo apt install -yf aoscbootstrap

      - name: Build tarballs
        run: sudo generate-releases buildkit container

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: os-amd64
          path: os-amd64

      - name: Remove artifact
        if: always()
        run: sudo rm -rf os-amd64
